### PR TITLE
adjusting the repo to my needs - wip

### PR DESCRIPTION
**Pull request by pflajszer**

### CODE REVIEW

**Review by 8cH9azbsFifZ — COMMENTED** [review]
Done

**Comment by pflajszer** [comment]
apologies, this was supposed to be a PR to my fork rather than the source repo. Having said that, I might have found some things that could improve this. Those include:
- using env vars instead of hardcoded credentials when building the container
- allow passing bool arg GET_LATEST to control if we download all data or call garmindb with `--latest` flag
- improved Makefile commands to build, run and clean up
- adding crontab job to run the latest script on schedule to keep up to date

would you be interested in any of those changes or should I not bother?

**Comment by 8cH9azbsFifZ** [comment]
If you try the pull request once again, I will merge your changes :)

**Comment by pflajszer** [comment]
no worries. I'll get the changes right and will open another PR then!

**Pull request closed without merging**
